spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:user_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD}

jwt:
  # 64-byte Base64-encoded secret key
  secret-key: ${JWT_SECRET_KEY}
  # Access Token validity period (1 hour = 3600000 ms)
  access-token-validity-in-ms: 3600000
  # Refresh Token validity period (14 days = 1209600000 ms)
  refresh-token-validity-in-ms: 1209600000